package com.example.weather.Utils;

public class IconCodeToDrawableID {
    public static String findDrawableId(String iconCode) {
        switch(iconCode) {
            case "100":
                return "_baitianqing";
            case "101":
            case "102":
            case "103":
                return "_qingtianduoyun";
            case "104":
                return "_yin";
            case "150":
                return "_yejianqing";
            case "151":
            case "152":
            case "153":
                return "_yewanduoyun";
            case "300":
            case "301":
                return "_baitianzhenyu";
            case "302":
            case "303":
            case "304":
                return "_leizhenyu";
            case "305":
                return "_xiaoyu";
            case "306":
                return "_zhongyu";
            case "307":
                return "_dayu";
            case "308":
                return "_tedabaoyu";
            case "309":
                return "_xiaoxue";
            case "310":
                return "_baoyu";
            case "311":
                return "_dabaoyu";
            case "312":
                return "_tedabaoyu";
            case "313":
                return "_dongyu";
            case "314":
                return "_xiaoyu";
            case "315":
                return "_zhongyu";
            case "316":
                return "_dayu";
            case "317":
                return "_baoyu";
            case "318":
                return "_dabaoyu";
            case "350":
            case "351":
                return "_yewanzhenyu";
            case "399":
                return "_zhongyu";
            case "400":
                return "_xiaoxue";
            case "401":
                return "_zhongxue";
            case "402":
                return "_daxue";
            case "403":
                return "_baoxue";
            case "404":
                return "_yujiaxue";
            case "405":
                return "_yujiaxue";
            case "406":
                return "_zhenyujiaxue";
            case "407":
                return "_qingtianzhenxue";
            case "408":
                return "_xiaoxue";
            case "409":
                return "_zhongxue";
            case "410":
                return "_daxue";
            case "456":
                return "_zhenyujiaxue";
            case "457":
                return "_qingtianzhenxue";
            case "499":
                return "_zhongxue";
            case "500":
            case "501":
            case "502":
                return "_wumai";
            case "503":
            case "504":
                return "_fuchen";
            case "507":
            case "508":
                return "_shachenbao";
            case "509":
            case "510":
            case "511":
            case "512":
            case "513":
            case "514":
            case "515":
                return "_wumai";
            case "900":
                return "_reqiwengao";
            case "901":
                return "_lengqiwendi";
            case "999":
                return "_qingtianduoyun";
            default:
                return "_qingtianduoyun";
        }
    }
}
